### ISSUE TITLE
Remove unplayable songs interaction w/ other extensions

### ISSUE THREAD

**Issue by CrazeLadd** [Resxt/Spicetify-Extensions#2]
So, it seems like the "Remove unplayable songs" extension negatively interacts with a bunch of other Spicetify extensions. When "Remove unplayable songs" is installed, any and all options in the right-click menu disappear (e.g., Shuffle+, Play Next, Copy Info, View Song Stats, etc.).

I don't know what causes this, but I'm hoping that there ends up being some fix :)

**Comment by Resxt** [comment]
Hello @CrazeLadd, thanks for your report!

There seems indeed to be a problem with the extension since, after testing it, the context menu (when right clicking a playlist) did show everything but didn't show "remove unplayable songs".

To be frank I don't know why it was working before when I released it (tested it with someone else as well) and now it doesn't since I've been told there have been no changes made in the meantime but whatever.

Someone gave me the solution and it works fine on my side now.
I pushed an update so if you use the marketplace it should automatically update for you in the upcoming days.
If you don't then delete the previous file and use the new one. Might need to re-apply the extension as well.

Please let me know how this goes for you (keep in mind that the marketplace can take several days to update my extension)

**Comment by CrazeLadd** [comment]
I've re-added the extension and am having no issues with it. I can thankfully see all the other menu options and am very happy now :D
