### ISSUE TITLE
CrossFade / Cross Dissolve?

### ISSUE THREAD

**Issue by CodeStudent123** [Resxt/Spicetify-Extensions#3]
_This is for the Skip Song Part Extension._ 

Is there any possible way to add crossfade/cross dissolve between segments skipped?

It would make songs a **LOT** smoother with cleaner transitions 👍

Perhaps there’s a way to leverage the crossfade and automix in Spotify?

**Comment by Resxt** [comment]
Hello @PrismBoy123 

There is no built-in way of doing that that I could easily implement.
I asked other developers if they knew anything like this but the only way of doing this seems to be one of these:
- Dig deep into Spotify's code and hopefully find how to recreate crossfade (too long, not even sure it's possible)
- Recreate a "fake" crossfade by manually lowering the client's sound by let's say 15% every 0.5s over the span of 3s and then increasing it the same way after skipping (not a real crossfade, hand-made so not perfect, won't work properly if the user modifies the volume during the process)

So for this I won't look into it since the solutions available seems to be really long/hard/impossible or to provide an half baked "crossfade" that's not even really one.
If you ever find someone who knows how to do that or some code I could take a look at or anything feel free to reply but until then I won't be looking into this more as it doesn't seem feasible, at least with my skill and knowledge
