### ISSUE TITLE
Idea for a new extension

### ISSUE THREAD

**Issue by plopin3472** [Resxt/Spicetify-Extensions#5]
Hey, idk anything about apis, github nor coding stuff, but heres my idea:

Option to disable ''Spotify Connect'', which disables all ways of device recognition (hence listening together).

https://community.spotify.com/t5/Live-Ideas/Connect-Option-to-deactivate-Spotify-Connect/idi-p/729015 btw, was suggested a while ago for Spotify, but it's obvious they won't implement it -I find this function annoying, not having any control over it since release nor forgetting devices (can't do that in windows) that are available when putting on a tune.

**Comment by plopin3472** [comment]
I found you to be the most situable when looking at Spicetify extensions, but sadly didn't saw anything related to connect, probably something obvious doesn't allow it  (idk)? Although I don't know if you're still around this stuff anymore.

**Comment by Resxt** [comment]
Hello @plopin3472 

I don't know if it's possible to mess with the Connect part of Spotify, never looked into it and never found any API shared by Spicetify or anything so I can't give any final answer on that.

One thing I know is that you can easily hide the Connect button with a simple CSS snippet if you simply don't want to see it.

As for actually editing the way it works I won't take a look at it because I'm not into developing extensions on Spicetify at the time.

**Comment by plopin3472** [comment]
> Hello @plopin3472
> 
> I don't know if it's possible to mess with the Connect part of Spotify, never looked into it and never found any API shared by Spicetify or anything so I can't give any final answer on that.
> 
> One thing I know is that you can easily hide the Connect button with a simple CSS snippet if you simply don't want to see it.
> 
> As for actually editing the way it works I won't take a look at it because I'm not into developing extensions on Spicetify at the time.

well turns out I thought that other devices could take control of the music playing, but instead they're only speakers and have no other purpose, so nothing that big if the main device connects to the others.
