### ISSUE TITLE
the discography to playlist doesn't add all songs from an artist

### ISSUE THREAD

**Issue by LjamGamer** [Resxt/Spicetify-Extensions#6]
![Screenshot (43)](https://github.com/user-attachments/assets/01edc905-5337-4366-8024-799d20d22e21)

**Comment by Resxt** [comment]
Hello @LjamGamer 

This is because it found the song before it looked at the album, as a single or from another album
This isn't perfect and that's something I would like to improve some day but as of now that's how it is, if you search up the "missing songs" in the playlist you'll see they're there, just not where you might expect them sometimes

![image](https://github.com/user-attachments/assets/ba5b8c1e-a9ea-459d-a1a7-80876fbd0781)
